language: python

sudo: false

python:
 - "3.5"
 - "3.4"
 - "3.3"
 - "2.7"

install: 
    - pip install -Ue .[test,build]
    - pip install coveralls

script: 
    - coverage run --source pysorter setup.py test

after_success:
 - coveralls
